In [23]:
import numpy as np
import pandas as pd
import sklearn

In [24]:
X_test = pd.read_csv(r"TEST.csv")
X_test = X_test.drop("ID", axis=1)
df_train = pd.read_csv(r"TRAIN.csv")

In [25]:
df_train

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F39,F40,F41,F42,F43,F44,F45,F46,F47,Class
0,0.185570,0.004568,0.005362,0.003335,0.005415,0.004895,0.012764,0.120138,0.140450,3.361753,...,0.041526,-0.230857,0.003310,0.042250,0.005975,0.002104,0.013878,0.001518,0.011347,0
1,0.369536,0.003983,0.003386,0.004902,0.007570,0.012136,0.118050,0.323925,0.132093,2.766117,...,-0.141285,-6.222857,0.834177,0.227968,0.018463,-0.020487,0.001246,0.007489,0.008724,1
2,0.602510,0.008442,0.012961,0.012870,0.046885,0.115401,0.065688,0.306677,0.498805,4.521201,...,0.011334,10.335251,-0.276614,-0.198900,-0.012756,0.014286,-0.001866,0.002687,0.013452,1
3,0.347957,0.064721,0.013611,0.011541,0.006492,0.008690,0.013192,0.164553,0.298665,3.170847,...,0.190479,2.864912,-1.921939,0.891690,1.108098,0.635431,0.081368,-0.000225,0.009166,0
4,0.233653,0.012217,0.010088,0.022095,0.026040,0.015062,0.016063,0.084648,0.213367,8.150943,...,0.203164,0.001812,-0.092731,0.005280,-0.213985,0.032195,0.002081,0.028930,-0.025912,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43771,1.231065,0.008631,0.010488,0.030072,0.224300,0.384893,0.452580,0.878004,0.583311,4.336341,...,0.076438,-10.673305,0.874835,0.035450,0.001390,-0.003333,0.002385,0.001182,-0.010616,1
43772,1.576213,0.019906,0.015115,0.034719,0.347274,0.913438,0.240656,0.469324,1.118124,3.395661,...,-0.033483,-19.302853,5.744947,0.373802,0.006406,-0.008244,-0.081317,-0.007015,-0.001864,1
43773,0.523951,0.006851,0.012379,0.008150,0.012631,0.012130,0.033749,0.150855,0.500064,3.677857,...,0.051253,0.825418,0.006428,-0.012533,-0.034026,0.000177,0.005071,0.005763,0.005489,0
43774,0.313915,0.003392,0.004212,0.004475,0.004765,0.005470,0.017687,0.034267,0.311377,2.097170,...,-0.012220,-0.630316,-0.006486,-0.042303,0.037734,0.039146,-0.008112,-0.001419,0.000728,1
43775,0.206646,0.014795,0.012043,0.020157,0.044076,0.029703,0.021559,0.108707,0.163788,3.503771,...,-0.034282,0.027310,-0.197855,-0.003869,-0.039651,-0.009938,0.006735,0.000255,-0.020324,1

In [26]:
X_train = df_train.drop("Class", axis=1)
X_train

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F38,F39,F40,F41,F42,F43,F44,F45,F46,F47
0,0.185570,0.004568,0.005362,0.003335,0.005415,0.004895,0.012764,0.120138,0.140450,3.361753,...,2.826142,0.041526,-0.230857,0.003310,0.042250,0.005975,0.002104,0.013878,0.001518,0.011347
1,0.369536,0.003983,0.003386,0.004902,0.007570,0.012136,0.118050,0.323925,0.132093,2.766117,...,2.955462,-0.141285,-6.222857,0.834177,0.227968,0.018463,-0.020487,0.001246,0.007489,0.008724
2,0.602510,0.008442,0.012961,0.012870,0.046885,0.115401,0.065688,0.306677,0.498805,4.521201,...,3.423784,0.011334,10.335251,-0.276614,-0.198900,-0.012756,0.014286,-0.001866,0.002687,0.013452
3,0.347957,0.064721,0.013611,0.011541,0.006492,0.008690,0.013192,0.164553,0.298665,3.170847,...,2.473058,0.190479,2.864912,-1.921939,0.891690,1.108098,0.635431,0.081368,-0.000225,0.009166
4,0.233653,0.012217,0.010088,0.022095,0.026040,0.015062,0.016063,0.084648,0.213367,8.150943,...,7.595287,0.203164,0.001812,-0.092731,0.005280,-0.213985,0.032195,0.002081,0.028930,-0.025912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43771,1.231065,0.008631,0.010488,0.030072,0.224300,0.384893,0.452580,0.878004,0.583311,4.336341,...,3.272185,0.076438,-10.673305,0.874835,0.035450,0.001390,-0.003333,0.002385,0.001182,-0.010616
43772,1.576213,0.019906,0.015115,0.034719,0.347274,0.913438,0.240656,0.469324,1.118124,3.395661,...,2.916853,-0.033483,-19.302853,5.744947,0.373802,0.006406,-0.008244,-0.081317,-0.007015,-0.001864
43773,0.523951,0.006851,0.012379,0.008150,0.012631,0.012130,0.033749,0.150855,0.500064,3.677857,...,2.750475,0.051253,0.825418,0.006428,-0.012533,-0.034026,0.000177,0.005071,0.005763,0.005489
43774,0.313915,0.003392,0.004212,0.004475,0.004765,0.005470,0.017687,0.034267,0.311377,2.097170,...,1.667138,-0.012220,-0.630316,-0.006486,-0.042303,0.037734,0.039146,-0.008112,-0.001419,0.000728
43775,0.206646,0.014795,0.012043,0.020157,0.044076,0.029703,0.021559,0.108707,0.163788,3.503771,...,2.854770,-0.034282,0.027310,-0.197855,-0.003869,-0.039651,-0.009938,0.006735,0.000255,-0.020324

In [27]:
y_train = df_train["Class"]
y_train

0        0
1        1
2        1
3        0
4        1
        ..
43771    1
43772    1
43773    0
43774    1
43775    1
Name: Class, Length: 43776, dtype: int64

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [29]:
X_test.shape

(10944, 47)

In [32]:
skew_values = X=df_train.skew(numeric_only=True)
print(skew_values)

F01        3.502914
F02        4.113035
F03        6.486684
F04        6.154857
F05        5.842776
F06        5.478422
F07        5.725355
F08        3.194014
F09        3.617396
F10        9.731940
F11        2.343764
F12        1.528021
F13        1.974930
F14        3.345408
F15        4.322090
F16        6.551304
F17        7.141235
F18        7.899958
F19        6.606499
F20       43.611189
F21        3.804576
F22        5.209466
F23        4.289016
F24        5.660693
F25        5.093701
F26        5.581533
F27        6.016508
F28        3.215145
F29        3.603974
F30      110.192365
F31        2.173298
F32        2.901455
F33        5.511146
F34       16.133662
F35       31.909529
F36       39.363202
F37       43.370430
F38       48.785096
F39       64.877219
F40       -0.002409
F41        0.042753
F42        0.036159
F43        3.099720
F44       11.810184
F45       23.766865
F46      -20.034829
F47      -27.717648
Class      0.427690
dtype: float64

In [ ]:
X_trans = df_train.drop('Class', axis=1)

In [38]:
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(method="yeo-johnson")

skewed_cols = X_trans.skew(numeric_only=True)
skewed_cols = skewed_cols[abs(skewed_cols) > 1].index
df_train[skewed_cols] = pt.fit_transform(df_train[skewed_cols])

In [39]:
X_train = df_train.drop("Class", axis=1)
y_train = df_train["Class"]

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

c:\Users\Gourav Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [41]:
y_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [42]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train, y_train, cv=5, scoring="f1")

print(scores)
print("Mean F1:", scores.mean())

[0.58036521 0.60024687 0.59759122 0.58705756 0.60183551]
Mean F1: 0.593419274208048

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

c:\Users\Gourav Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [45]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train, y_train, cv=5, scoring="f1")

print(scores)
print("Mean F1:", scores.mean())

[0.97737291 0.97559541 0.97741935 0.97434385 0.9787608 ]
Mean F1: 0.9766984656556282

In [46]:
y_pred

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [49]:
pred = pd.DataFrame(y_pred, columns=['Class'])

In [50]:
print(pred)

       Class
0          0
1          0
2          0
3          0
4          0
...      ...
10939      0
10940      1
10941      1
10942      0
10943      0

[10944 rows x 1 columns]

In [51]:
pred.to_csv('FINAL.csv', index=True)